EE-6374 total monthly payments for salaried assessments
UKHomeOffice/pttg-ip-api pull request #127
Opened 2018-09-24 15:13 UTC by owainrobertsbjss

Made it so that for salaried incomes, payments of the same month or week are summed and the validation performed against the total.

- Created an "add" method for Income which will return a new Income with the payments summed. In order to add two Income instances the month or week must be the same and the employment reference must be the same.

-  Rearranged the main if statement in CatAMonthlyValidator.financialCheckForMonthlySalaried using an early return so that the more complicated logic could be indented less.

- Added new helper functions in IncomeValidationHelper and refactored some existing ones to suit the new logic. Most noteworthy is that sorting of Incomes by date has been moved into its own method to be called in the validator, rather than as part of the filterIncomesByDates() call.

- Added logging to the IncomeFrequencyCalculator for when it calculates the frequency using payment dates rather than month/week pay numbers. This is so that it can be seen in production if this code is actually ever used.

- Moved all BDD tests for EE-6374 out of the WIP folder, except for the ones relating to partner incomes as Cat A checks don't yet handle this.

2018-09-25 10:07 UTC, mikehalmaho requested changes

2018-09-25 10:07 UTC, mikehalmaho commented on src/main/java/uk/gov/digital/ho/proving/income/validator/CatASalariedMonthlyIncomeValidator.java
> -                removeDuplicates(applicantIncome.incomeRecord().paye()),
As we can get duplicates from HMRC we need to keep this - but please add tests as you suggested.

2018-09-25 10:07 UTC, mikehalmaho commented on src/main/java/uk/gov/digital/ho/proving/income/validator/CatASalariedMonthlyIncomeValidator.java
> +            return employmentCheck.equals(EmploymentCheck.FAILED_THRESHOLD) ? IncomeValidationStatus.MONTHLY_VALUE_BELOW_THRESHOLD : IncomeValidationStatus.MULTIPLE_EMPLOYERS;
I know this was not added by you, but I'm not keen on the mix of styles - if / else / ternary.

2018-09-25 10:07 UTC, mikehalmaho commented on src/main/java/uk/gov/digital/ho/proving/income/validator/FrequencyCalculator.java
> +            frequency = Frequency.UNKNOWN;
Can we add a range to the frequency enum, and a method that accepts daysBetweenPayments and returns the relevant enum?

2018-09-25 10:07 UTC, mikehalmaho commented on src/test/java/uk/gov/digital/ho/proving/income/validator/CatASalariedTestData.java
> +        incomes.add(new Income(amount("1600"), raisedDate, 6, null, PIZZA_HUT_PAYE_REF ));
Please review all test data generation - it might be better to a) automate (instead of having pages of test data) and b) make the dates relative.

2018-09-25 10:07 UTC, mikehalmaho commented on src/test/specs/API-v3-wip/06 - EE-6347 Total Monthly Payments for Salaried Assessments NOT PASS.feature
> +            | Category A Monthly Salary | Financial requirement met | false            |
Please can you review the negative tests and check failure reason if possible?

2018-09-25 15:40 UTC, owainrobertsbjss commented
@mikehalmaho I believe I've made all requested changes. In CatASalariedTestData I've only made the data generation dynamic or more concise where it was feasible. I think some of the methods are easier to understand in the current form.

2018-09-26 08:58 UTC, mikehalmaho approved these changes

2018-09-26 09:02 UTC, merged